# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acquisition.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 100, 441, 71))
        self.groupBox.setObjectName("groupBox")
        self.pushInitTDC = QtWidgets.QPushButton(self.groupBox)
        self.pushInitTDC.setGeometry(QtCore.QRect(50, 40, 75, 23))
        self.pushInitTDC.setObjectName("pushInitTDC")
        self.pushDeinitTDC = QtWidgets.QPushButton(self.groupBox)
        self.pushDeinitTDC.setGeometry(QtCore.QRect(140, 40, 75, 23))
        self.pushDeinitTDC.setObjectName("pushDeinitTDC")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(50, 10, 291, 31))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.iniFileLabel = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.iniFileLabel.setObjectName("iniFileLabel")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iniFileLabel)
        self.iniFileLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        self.iniFileLineEdit.setEnabled(False)
        self.iniFileLineEdit.setObjectName("iniFileLineEdit")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iniFileLineEdit)
        self.pushSelectIni = QtWidgets.QPushButton(self.groupBox)
        self.pushSelectIni.setEnabled(False)
        self.pushSelectIni.setGeometry(QtCore.QRect(350, 10, 75, 23))
        self.pushSelectIni.setObjectName("pushSelectIni")
        self.groupBox_Select_ini = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_Select_ini.setGeometry(QtCore.QRect(249, 39, 171, 31))
        self.groupBox_Select_ini.setObjectName("groupBox_Select_ini")
        self.radioButton_FreeRun_ini = QtWidgets.QRadioButton(self.groupBox_Select_ini)
        self.radioButton_FreeRun_ini.setGeometry(QtCore.QRect(10, 10, 82, 17))
        self.radioButton_FreeRun_ini.setObjectName("radioButton_FreeRun_ini")
        self.radioButton_ExtStart_ini = QtWidgets.QRadioButton(self.groupBox_Select_ini)
        self.radioButton_ExtStart_ini.setGeometry(QtCore.QRect(90, 10, 82, 17))
        self.radioButton_ExtStart_ini.setChecked(True)
        self.radioButton_ExtStart_ini.setObjectName("radioButton_ExtStart_ini")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 180, 441, 351))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushConnectProdigy = QtWidgets.QPushButton(self.groupBox_2)
        self.pushConnectProdigy.setGeometry(QtCore.QRect(30, 20, 131, 23))
        self.pushConnectProdigy.setObjectName("pushConnectProdigy")
        self.pushDisconnectProdigy = QtWidgets.QPushButton(self.groupBox_2)
        self.pushDisconnectProdigy.setGeometry(QtCore.QRect(200, 20, 221, 23))
        self.pushDisconnectProdigy.setObjectName("pushDisconnectProdigy")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 50, 137, 248))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.deflectionXLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.deflectionXLabel.setObjectName("deflectionXLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.deflectionXLabel)
        self.deflectionXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.deflectionXDoubleSpinBox.setDecimals(5)
        self.deflectionXDoubleSpinBox.setMinimum(-1.0)
        self.deflectionXDoubleSpinBox.setMaximum(1.0)
        self.deflectionXDoubleSpinBox.setSingleStep(0.001)
        self.deflectionXDoubleSpinBox.setProperty("value", -0.0558)
        self.deflectionXDoubleSpinBox.setObjectName("deflectionXDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.deflectionXDoubleSpinBox)
        self.deflectionYLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.deflectionYLabel.setObjectName("deflectionYLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.deflectionYLabel)
        self.deflectionYDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.deflectionYDoubleSpinBox.setDecimals(5)
        self.deflectionYDoubleSpinBox.setMinimum(-1.0)
        self.deflectionYDoubleSpinBox.setMaximum(1.0)
        self.deflectionYDoubleSpinBox.setSingleStep(0.001)
        self.deflectionYDoubleSpinBox.setProperty("value", 0.0346)
        self.deflectionYDoubleSpinBox.setObjectName("deflectionYDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.deflectionYDoubleSpinBox)
        self.l1Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.l1Label.setObjectName("l1Label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.l1Label)
        self.l1DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.l1DoubleSpinBox.setDecimals(5)
        self.l1DoubleSpinBox.setMinimum(-1.0)
        self.l1DoubleSpinBox.setMaximum(1.0)
        self.l1DoubleSpinBox.setSingleStep(0.001)
        self.l1DoubleSpinBox.setProperty("value", 0.1334)
        self.l1DoubleSpinBox.setObjectName("l1DoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.l1DoubleSpinBox)
        self.preDeflXLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.preDeflXLabel.setObjectName("preDeflXLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.preDeflXLabel)
        self.preDeflXDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.preDeflXDoubleSpinBox.setDecimals(5)
        self.preDeflXDoubleSpinBox.setMinimum(-1.0)
        self.preDeflXDoubleSpinBox.setMaximum(1.0)
        self.preDeflXDoubleSpinBox.setSingleStep(0.001)
        self.preDeflXDoubleSpinBox.setProperty("value", 0.01655)
        self.preDeflXDoubleSpinBox.setObjectName("preDeflXDoubleSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.preDeflXDoubleSpinBox)
        self.preDeflYLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.preDeflYLabel.setObjectName("preDeflYLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.preDeflYLabel)
        self.preDeflYDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.preDeflYDoubleSpinBox.setDecimals(5)
        self.preDeflYDoubleSpinBox.setMinimum(-1.0)
        self.preDeflYDoubleSpinBox.setMaximum(1.0)
        self.preDeflYDoubleSpinBox.setSingleStep(0.001)
        self.preDeflYDoubleSpinBox.setProperty("value", -0.03835)
        self.preDeflYDoubleSpinBox.setObjectName("preDeflYDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.preDeflYDoubleSpinBox)
        self.l2Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.l2Label.setObjectName("l2Label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.l2Label)
        self.l2DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.l2DoubleSpinBox.setEnabled(False)
        self.l2DoubleSpinBox.setDecimals(5)
        self.l2DoubleSpinBox.setMinimum(-1.0)
        self.l2DoubleSpinBox.setMaximum(1.0)
        self.l2DoubleSpinBox.setSingleStep(0.001)
        self.l2DoubleSpinBox.setProperty("value", 0.0151)
        self.l2DoubleSpinBox.setObjectName("l2DoubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.l2DoubleSpinBox)
        self.focus1Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.focus1Label.setObjectName("focus1Label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.focus1Label)
        self.focus1DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.focus1DoubleSpinBox.setDecimals(5)
        self.focus1DoubleSpinBox.setMinimum(-1.0)
        self.focus1DoubleSpinBox.setMaximum(1.0)
        self.focus1DoubleSpinBox.setSingleStep(0.0001)
        self.focus1DoubleSpinBox.setProperty("value", 0.0)
        self.focus1DoubleSpinBox.setObjectName("focus1DoubleSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.focus1DoubleSpinBox)
        self.focus2Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.focus2Label.setObjectName("focus2Label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.focus2Label)
        self.focus2DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.focus2DoubleSpinBox.setMinimum(-1.0)
        self.focus2DoubleSpinBox.setMaximum(1.0)
        self.focus2DoubleSpinBox.setSingleStep(0.0001)
        self.focus2DoubleSpinBox.setObjectName("focus2DoubleSpinBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.focus2DoubleSpinBox)
        self.auxVoltageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.auxVoltageLabel.setObjectName("auxVoltageLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.auxVoltageLabel)
        self.auxVoltageSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.auxVoltageSpinBox.setEnabled(False)
        self.auxVoltageSpinBox.setMinimum(-10)
        self.auxVoltageSpinBox.setMaximum(10)
        self.auxVoltageSpinBox.setObjectName("auxVoltageSpinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.auxVoltageSpinBox)
        self.pushSaveVoltages = QtWidgets.QPushButton(self.groupBox_2)
        self.pushSaveVoltages.setGeometry(QtCore.QRect(20, 290, 75, 23))
        self.pushSaveVoltages.setObjectName("pushSaveVoltages")
        self.pushLoadVoltages = QtWidgets.QPushButton(self.groupBox_2)
        self.pushLoadVoltages.setGeometry(QtCore.QRect(100, 290, 75, 21))
        self.pushLoadVoltages.setObjectName("pushLoadVoltages")
        self.pushApplyVoltages = QtWidgets.QPushButton(self.groupBox_2)
        self.pushApplyVoltages.setGeometry(QtCore.QRect(280, 270, 101, 41))
        self.pushApplyVoltages.setObjectName("pushApplyVoltages")
        self.pushSetSafeState = QtWidgets.QPushButton(self.groupBox_2)
        self.pushSetSafeState.setGeometry(QtCore.QRect(280, 320, 101, 23))
        self.pushSetSafeState.setObjectName("pushSetSafeState")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(200, 50, 221, 220))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.lensModeLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.lensModeLabel.setObjectName("lensModeLabel")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lensModeLabel)
        self.lensModeComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.lensModeComboBox.setObjectName("lensModeComboBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lensModeComboBox)
        self.scanRangeLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.scanRangeLabel.setObjectName("scanRangeLabel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.scanRangeLabel)
        self.scanRangeComboBox = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.scanRangeComboBox.setCurrentText("")
        self.scanRangeComboBox.setObjectName("scanRangeComboBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.scanRangeComboBox)
        self.kineticEnergyLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.kineticEnergyLabel.setObjectName("kineticEnergyLabel")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.kineticEnergyLabel)
        self.kineticEnergySpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.kineticEnergySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kineticEnergySpinBox.setMaximum(1500)
        self.kineticEnergySpinBox.setProperty("value", 0)
        self.kineticEnergySpinBox.setObjectName("kineticEnergySpinBox")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.kineticEnergySpinBox)
        self.passEnergyLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.passEnergyLabel.setObjectName("passEnergyLabel")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.passEnergyLabel)
        self.passEnergySpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.passEnergySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.passEnergySpinBox.setMaximum(250)
        self.passEnergySpinBox.setProperty("value", 20)
        self.passEnergySpinBox.setObjectName("passEnergySpinBox")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passEnergySpinBox)
        self.detectorVoltageLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.detectorVoltageLabel.setObjectName("detectorVoltageLabel")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.detectorVoltageLabel)
        self.detectorVoltageSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.detectorVoltageSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.detectorVoltageSpinBox.setMaximum(2500)
        self.detectorVoltageSpinBox.setProperty("value", 2150)
        self.detectorVoltageSpinBox.setObjectName("detectorVoltageSpinBox")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.detectorVoltageSpinBox)
        self.dLDVoltageLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.dLDVoltageLabel.setObjectName("dLDVoltageLabel")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.dLDVoltageLabel)
        self.dLDVoltageSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.dLDVoltageSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dLDVoltageSpinBox.setMaximum(300)
        self.dLDVoltageSpinBox.setObjectName("dLDVoltageSpinBox")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dLDVoltageSpinBox)
        self.biasElectronsLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.biasElectronsLabel.setObjectName("biasElectronsLabel")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.biasElectronsLabel)
        self.biasElectronsSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.biasElectronsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.biasElectronsSpinBox.setMaximum(300)
        self.biasElectronsSpinBox.setProperty("value", 220)
        self.biasElectronsSpinBox.setObjectName("biasElectronsSpinBox")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.biasElectronsSpinBox)
        self.coilCurrentLabel = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.coilCurrentLabel.setObjectName("coilCurrentLabel")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.coilCurrentLabel)
        self.coilCurrentSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.coilCurrentSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.coilCurrentSpinBox.setMinimum(-100)
        self.coilCurrentSpinBox.setProperty("value", 0)
        self.coilCurrentSpinBox.setObjectName("coilCurrentSpinBox")
        self.formLayout_5.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.coilCurrentSpinBox)
        self.lineVoltages = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineVoltages.setEnabled(False)
        self.lineVoltages.setGeometry(QtCore.QRect(20, 320, 221, 20))
        self.lineVoltages.setObjectName("lineVoltages")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 10, 441, 81))
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 23, 231, 52))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dataFolderLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.dataFolderLabel.setObjectName("dataFolderLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dataFolderLabel)
        self.dataFolderLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.dataFolderLineEdit.setObjectName("dataFolderLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dataFolderLineEdit)
        self.fileNameLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.fileNameLabel.setObjectName("fileNameLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fileNameLabel)
        self.fileNameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.fileNameLineEdit.setObjectName("fileNameLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fileNameLineEdit)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 20, 134, 56))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushBrowseFolder = QtWidgets.QPushButton(self.layoutWidget)
        self.pushBrowseFolder.setObjectName("pushBrowseFolder")
        self.verticalLayout.addWidget(self.pushBrowseFolder)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.runningNoLabel = QtWidgets.QLabel(self.layoutWidget)
        self.runningNoLabel.setObjectName("runningNoLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.runningNoLabel)
        self.runningNoSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.runningNoSpinBox.setMaximum(100000)
        self.runningNoSpinBox.setObjectName("runningNoSpinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.runningNoSpinBox)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(520, 10, 431, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.plotCountsLog = QtWidgets.QGraphicsView(self.groupBox_4)
        self.plotCountsLog.setGeometry(QtCore.QRect(10, 60, 351, 211))
        self.plotCountsLog.setObjectName("plotCountsLog")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(40, 10, 239, 39))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdCPS = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdCPS.setGeometry(QtCore.QRect(240, 20, 121, 31))
        self.lcdCPS.setDigitCount(7)
        self.lcdCPS.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdCPS.setObjectName("lcdCPS")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 540, 441, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.logBrowser = QtWidgets.QTextBrowser(self.groupBox_5)
        self.logBrowser.setGeometry(QtCore.QRect(15, 21, 411, 51))
        self.logBrowser.setObjectName("logBrowser")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(520, 290, 431, 51))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushStaticAcquire = QtWidgets.QPushButton(self.groupBox_6)
        self.pushStaticAcquire.setGeometry(QtCore.QRect(190, 20, 75, 23))
        self.pushStaticAcquire.setObjectName("pushStaticAcquire")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(20, 20, 181, 24))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.acquisitionTimeSecsLabel = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.acquisitionTimeSecsLabel.setObjectName("acquisitionTimeSecsLabel")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.acquisitionTimeSecsLabel)
        self.acquisitionTimeSecsSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.acquisitionTimeSecsSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.acquisitionTimeSecsSpinBox.setMaximum(10000)
        self.acquisitionTimeSecsSpinBox.setProperty("value", 60)
        self.acquisitionTimeSecsSpinBox.setObjectName("acquisitionTimeSecsSpinBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acquisitionTimeSecsSpinBox)
        self.pushStaticAbort = QtWidgets.QPushButton(self.groupBox_6)
        self.pushStaticAbort.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.pushStaticAbort.setObjectName("pushStaticAbort")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(520, 340, 431, 421))
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_7)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 320, 233, 52))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.acquisitionTimePerStepSecsLabel = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.acquisitionTimePerStepSecsLabel.setObjectName("acquisitionTimePerStepSecsLabel")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.acquisitionTimePerStepSecsLabel)
        self.acquisitionTimePerStepSecsSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_6)
        self.acquisitionTimePerStepSecsSpinBox.setMinimum(1)
        self.acquisitionTimePerStepSecsSpinBox.setMaximum(10000)
        self.acquisitionTimePerStepSecsSpinBox.setObjectName("acquisitionTimePerStepSecsSpinBox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acquisitionTimePerStepSecsSpinBox)
        self.numberOfCyclesLabel = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.numberOfCyclesLabel.setObjectName("numberOfCyclesLabel")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.numberOfCyclesLabel)
        self.numberOfCyclesSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_6)
        self.numberOfCyclesSpinBox.setMinimum(1)
        self.numberOfCyclesSpinBox.setMaximum(100000)
        self.numberOfCyclesSpinBox.setObjectName("numberOfCyclesSpinBox")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.numberOfCyclesSpinBox)
        self.pushScanAcquire = QtWidgets.QPushButton(self.groupBox_7)
        self.pushScanAcquire.setGeometry(QtCore.QRect(240, 320, 75, 23))
        self.pushScanAcquire.setObjectName("pushScanAcquire")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 70, 401, 241))
        self.groupBox_8.setObjectName("groupBox_8")
        self.tableOfDelayRanges = QtWidgets.QTableWidget(self.groupBox_8)
        self.tableOfDelayRanges.setGeometry(QtCore.QRect(10, 20, 381, 151))
        self.tableOfDelayRanges.setRowCount(1)
        self.tableOfDelayRanges.setColumnCount(3)
        self.tableOfDelayRanges.setObjectName("tableOfDelayRanges")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0, 20))
        self.tableOfDelayRanges.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0, 20))
        self.tableOfDelayRanges.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 0, 0, 20))
        self.tableOfDelayRanges.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOfDelayRanges.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOfDelayRanges.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableOfDelayRanges.setItem(0, 2, item)
        self.tableOfDelayRanges.horizontalHeader().setDefaultSectionSize(91)
        self.tableOfDelayRanges.verticalHeader().setDefaultSectionSize(15)
        self.tableOfDelayRanges.verticalHeader().setMinimumSectionSize(15)
        self.tableOfDelayRanges.verticalHeader().setStretchLastSection(False)
        self.pushAddRow = QtWidgets.QPushButton(self.groupBox_8)
        self.pushAddRow.setGeometry(QtCore.QRect(10, 180, 75, 23))
        self.pushAddRow.setObjectName("pushAddRow")
        self.pushDeleteRow = QtWidgets.QPushButton(self.groupBox_8)
        self.pushDeleteRow.setGeometry(QtCore.QRect(90, 180, 86, 23))
        self.pushDeleteRow.setObjectName("pushDeleteRow")
        self.pushSaveScan = QtWidgets.QPushButton(self.groupBox_8)
        self.pushSaveScan.setEnabled(True)
        self.pushSaveScan.setGeometry(QtCore.QRect(230, 180, 75, 23))
        self.pushSaveScan.setObjectName("pushSaveScan")
        self.pushLoadScan = QtWidgets.QPushButton(self.groupBox_8)
        self.pushLoadScan.setEnabled(True)
        self.pushLoadScan.setGeometry(QtCore.QRect(310, 180, 75, 23))
        self.pushLoadScan.setObjectName("pushLoadScan")
        self.linePSScans = QtWidgets.QLineEdit(self.groupBox_8)
        self.linePSScans.setEnabled(False)
        self.linePSScans.setGeometry(QtCore.QRect(10, 210, 381, 21))
        self.linePSScans.setObjectName("linePSScans")
        self.pushInitPhaseShifter = QtWidgets.QPushButton(self.groupBox_7)
        self.pushInitPhaseShifter.setGeometry(QtCore.QRect(48, 23, 91, 23))
        self.pushInitPhaseShifter.setObjectName("pushInitPhaseShifter")
        self.pushScanAbort = QtWidgets.QPushButton(self.groupBox_7)
        self.pushScanAbort.setGeometry(QtCore.QRect(240, 350, 75, 23))
        self.pushScanAbort.setObjectName("pushScanAbort")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_7)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(160, 20, 160, 24))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.delayPsecLabel = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.delayPsecLabel.setObjectName("delayPsecLabel")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.delayPsecLabel)
        self.delayPsecSpinBox = QtWidgets.QSpinBox(self.formLayoutWidget_5)
        self.delayPsecSpinBox.setMaximum(5000)
        self.delayPsecSpinBox.setSingleStep(5)
        self.delayPsecSpinBox.setObjectName("delayPsecSpinBox")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.delayPsecSpinBox)
        self.pushSetPhaseShifter = QtWidgets.QPushButton(self.groupBox_7)
        self.pushSetPhaseShifter.setGeometry(QtCore.QRect(160, 50, 75, 23))
        self.pushSetPhaseShifter.setObjectName("pushSetPhaseShifter")
        self.lcdDelay = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdDelay.setGeometry(QtCore.QRect(250, 50, 71, 21))
        self.lcdDelay.setDigitCount(4)
        self.lcdDelay.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdDelay.setObjectName("lcdDelay")
        self.progressScan = QtWidgets.QProgressBar(self.groupBox_7)
        self.progressScan.setGeometry(QtCore.QRect(10, 390, 341, 23))
        self.progressScan.setProperty("value", 0)
        self.progressScan.setObjectName("progressScan")
        self.testPS = QtWidgets.QPushButton(self.groupBox_7)
        self.testPS.setGeometry(QtCore.QRect(380, 390, 41, 23))
        self.testPS.setObjectName("testPS")
        self.estTimeLine = QtWidgets.QLineEdit(self.groupBox_7)
        self.estTimeLine.setGeometry(QtCore.QRect(350, 350, 71, 20))
        self.estTimeLine.setObjectName("estTimeLine")
        self.estTimeLabel = QtWidgets.QLabel(self.groupBox_7)
        self.estTimeLabel.setGeometry(QtCore.QRect(350, 320, 71, 20))
        self.estTimeLabel.setObjectName("estTimeLabel")
        self.groupBox_Overlap2Picomotor = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Overlap2Picomotor.setGeometry(QtCore.QRect(40, 630, 441, 141))
        self.groupBox_Overlap2Picomotor.setObjectName("groupBox_Overlap2Picomotor")
        self.doubleSpinBox_CalAH = QtWidgets.QDoubleSpinBox(self.groupBox_Overlap2Picomotor)
        self.doubleSpinBox_CalAH.setGeometry(QtCore.QRect(30, 70, 62, 22))
        self.doubleSpinBox_CalAH.setDecimals(4)
        self.doubleSpinBox_CalAH.setMinimum(-99999.0)
        self.doubleSpinBox_CalAH.setMaximum(99999.99)
        self.doubleSpinBox_CalAH.setObjectName("doubleSpinBox_CalAH")
        self.doubleSpinBox_CalAV = QtWidgets.QDoubleSpinBox(self.groupBox_Overlap2Picomotor)
        self.doubleSpinBox_CalAV.setGeometry(QtCore.QRect(30, 100, 62, 22))
        self.doubleSpinBox_CalAV.setDecimals(4)
        self.doubleSpinBox_CalAV.setMinimum(-99999.0)
        self.doubleSpinBox_CalAV.setMaximum(99999.99)
        self.doubleSpinBox_CalAV.setObjectName("doubleSpinBox_CalAV")
        self.doubleSpinBox_CalBH = QtWidgets.QDoubleSpinBox(self.groupBox_Overlap2Picomotor)
        self.doubleSpinBox_CalBH.setGeometry(QtCore.QRect(100, 70, 62, 22))
        self.doubleSpinBox_CalBH.setDecimals(4)
        self.doubleSpinBox_CalBH.setMinimum(-99999.0)
        self.doubleSpinBox_CalBH.setMaximum(99999.99)
        self.doubleSpinBox_CalBH.setObjectName("doubleSpinBox_CalBH")
        self.doubleSpinBox_CalBV = QtWidgets.QDoubleSpinBox(self.groupBox_Overlap2Picomotor)
        self.doubleSpinBox_CalBV.setGeometry(QtCore.QRect(100, 100, 62, 22))
        self.doubleSpinBox_CalBV.setDecimals(4)
        self.doubleSpinBox_CalBV.setMinimum(-99999.0)
        self.doubleSpinBox_CalBV.setMaximum(99999.99)
        self.doubleSpinBox_CalBV.setObjectName("doubleSpinBox_CalBV")
        self.spinBox_StepA = QtWidgets.QSpinBox(self.groupBox_Overlap2Picomotor)
        self.spinBox_StepA.setEnabled(False)
        self.spinBox_StepA.setGeometry(QtCore.QRect(380, 70, 42, 22))
        self.spinBox_StepA.setReadOnly(False)
        self.spinBox_StepA.setMinimum(-9999)
        self.spinBox_StepA.setMaximum(9999)
        self.spinBox_StepA.setObjectName("spinBox_StepA")
        self.spinBox_StepB = QtWidgets.QSpinBox(self.groupBox_Overlap2Picomotor)
        self.spinBox_StepB.setEnabled(False)
        self.spinBox_StepB.setGeometry(QtCore.QRect(380, 100, 42, 22))
        self.spinBox_StepB.setMinimum(-9999)
        self.spinBox_StepB.setMaximum(9999)
        self.spinBox_StepB.setObjectName("spinBox_StepB")
        self.label_2 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 151, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 21, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 21, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_5.setGeometry(QtCore.QRect(50, 50, 21, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_6.setGeometry(QtCore.QRect(120, 50, 21, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_7.setGeometry(QtCore.QRect(220, 30, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_8.setGeometry(QtCore.QRect(230, 70, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_9.setGeometry(QtCore.QRect(230, 100, 31, 16))
        self.label_9.setObjectName("label_9")
        self.spinBox_DevH = QtWidgets.QSpinBox(self.groupBox_Overlap2Picomotor)
        self.spinBox_DevH.setGeometry(QtCore.QRect(260, 70, 42, 22))
        self.spinBox_DevH.setMinimum(-999999)
        self.spinBox_DevH.setMaximum(999999)
        self.spinBox_DevH.setObjectName("spinBox_DevH")
        self.spinBox_DevV = QtWidgets.QSpinBox(self.groupBox_Overlap2Picomotor)
        self.spinBox_DevV.setGeometry(QtCore.QRect(260, 100, 42, 22))
        self.spinBox_DevV.setMinimum(-99999)
        self.spinBox_DevV.setMaximum(99999)
        self.spinBox_DevV.setObjectName("spinBox_DevV")
        self.label_10 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_10.setGeometry(QtCore.QRect(360, 30, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_11.setGeometry(QtCore.QRect(360, 70, 21, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_12.setGeometry(QtCore.QRect(360, 100, 21, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_13.setGeometry(QtCore.QRect(320, 30, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_Overlap2Picomotor)
        self.label_14.setGeometry(QtCore.QRect(220, 50, 91, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "TDC"))
        self.pushInitTDC.setText(_translate("MainWindow", "Init"))
        self.pushDeinitTDC.setText(_translate("MainWindow", "Deinit"))
        self.iniFileLabel.setText(_translate("MainWindow", "Ini File"))
        self.pushSelectIni.setText(_translate("MainWindow", "Select"))
        self.groupBox_Select_ini.setTitle(_translate("MainWindow", "Select .ini file"))
        self.radioButton_FreeRun_ini.setText(_translate("MainWindow", "Free Run"))
        self.radioButton_ExtStart_ini.setText(_translate("MainWindow", "Ext. Start"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Prodigy"))
        self.pushConnectProdigy.setText(_translate("MainWindow", "Connect"))
        self.pushDisconnectProdigy.setText(_translate("MainWindow", "Disconnect"))
        self.deflectionXLabel.setText(_translate("MainWindow", "Deflection X"))
        self.deflectionYLabel.setText(_translate("MainWindow", "Deflection Y"))
        self.l1Label.setText(_translate("MainWindow", "L1 "))
        self.preDeflXLabel.setText(_translate("MainWindow", "Pre Defl X"))
        self.preDeflYLabel.setText(_translate("MainWindow", "Pre Defl Y"))
        self.l2Label.setText(_translate("MainWindow", "L2"))
        self.focus1Label.setText(_translate("MainWindow", "Focus1"))
        self.focus2Label.setText(_translate("MainWindow", "Focus2"))
        self.auxVoltageLabel.setText(_translate("MainWindow", "AuxVoltage"))
        self.pushSaveVoltages.setText(_translate("MainWindow", "Save"))
        self.pushLoadVoltages.setText(_translate("MainWindow", "Load"))
        self.pushApplyVoltages.setText(_translate("MainWindow", "Apply Voltages"))
        self.pushSetSafeState.setText(_translate("MainWindow", "Set Safe State"))
        self.lensModeLabel.setText(_translate("MainWindow", "Lens Mode"))
        self.scanRangeLabel.setText(_translate("MainWindow", "Scan Range"))
        self.kineticEnergyLabel.setText(_translate("MainWindow", "Kinetic Energy"))
        self.passEnergyLabel.setText(_translate("MainWindow", "Pass Energy"))
        self.detectorVoltageLabel.setText(_translate("MainWindow", "Detector Voltage"))
        self.dLDVoltageLabel.setText(_translate("MainWindow", "DLD Voltage"))
        self.biasElectronsLabel.setText(_translate("MainWindow", "Bias Electrons"))
        self.coilCurrentLabel.setText(_translate("MainWindow", "Coil Current"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Files"))
        self.dataFolderLabel.setText(_translate("MainWindow", "Data Folder"))
        self.fileNameLabel.setText(_translate("MainWindow", "File Name"))
        self.pushBrowseFolder.setText(_translate("MainWindow", "Browse"))
        self.runningNoLabel.setText(_translate("MainWindow", "Running No."))
        self.groupBox_4.setTitle(_translate("MainWindow", "Acquisition Stats"))
        self.label.setText(_translate("MainWindow", "Count Rate [cps]"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Event Log"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Static Acquisition"))
        self.pushStaticAcquire.setText(_translate("MainWindow", "Acquire"))
        self.acquisitionTimeSecsLabel.setText(_translate("MainWindow", "Acquisition Time [secs]"))
        self.pushStaticAbort.setText(_translate("MainWindow", "Abort"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Pump--Probe Scan"))
        self.acquisitionTimePerStepSecsLabel.setText(_translate("MainWindow", "Acquisition Time per Step [secs]"))
        self.numberOfCyclesLabel.setText(_translate("MainWindow", "Number of Cycles"))
        self.pushScanAcquire.setText(_translate("MainWindow", "Acquire"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Delays"))
        item = self.tableOfDelayRanges.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Start"))
        item = self.tableOfDelayRanges.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "End"))
        item = self.tableOfDelayRanges.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stepsize"))
        __sortingEnabled = self.tableOfDelayRanges.isSortingEnabled()
        self.tableOfDelayRanges.setSortingEnabled(False)
        item = self.tableOfDelayRanges.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableOfDelayRanges.item(0, 1)
        item.setText(_translate("MainWindow", "5000"))
        item = self.tableOfDelayRanges.item(0, 2)
        item.setText(_translate("MainWindow", "100"))
        self.tableOfDelayRanges.setSortingEnabled(__sortingEnabled)
        self.pushAddRow.setText(_translate("MainWindow", "Add Row"))
        self.pushDeleteRow.setText(_translate("MainWindow", "Delete Last Row"))
        self.pushSaveScan.setText(_translate("MainWindow", "Save Scans"))
        self.pushLoadScan.setText(_translate("MainWindow", "Load Scans"))
        self.pushInitPhaseShifter.setText(_translate("MainWindow", "Init Phase Shifter"))
        self.pushScanAbort.setText(_translate("MainWindow", "Abort"))
        self.delayPsecLabel.setText(_translate("MainWindow", "Delay [psec]"))
        self.pushSetPhaseShifter.setText(_translate("MainWindow", "Set Delay"))
        self.testPS.setText(_translate("MainWindow", "testPS"))
        self.estTimeLine.setPlaceholderText(_translate("MainWindow", "50 s"))
        self.estTimeLabel.setText(_translate("MainWindow", "Est. Time (s)"))
        self.groupBox_Overlap2Picomotor.setTitle(_translate("MainWindow", "Spatial Overlap Offset to Periscope Picomotor Calculation"))
        self.label_2.setText(_translate("MainWindow", "Motor Calibration Settings"))
        self.label_3.setText(_translate("MainWindow", "H"))
        self.label_4.setText(_translate("MainWindow", "V"))
        self.label_5.setText(_translate("MainWindow", "A"))
        self.label_6.setText(_translate("MainWindow", "B"))
        self.label_7.setText(_translate("MainWindow", "Spatial Deviation"))
        self.label_8.setText(_translate("MainWindow", "Hor"))
        self.label_9.setText(_translate("MainWindow", "Ver"))
        self.label_10.setText(_translate("MainWindow", "Motor Steps"))
        self.label_11.setText(_translate("MainWindow", "A"))
        self.label_12.setText(_translate("MainWindow", "B"))
        self.label_13.setText(_translate("MainWindow", "---->"))
        self.label_14.setText(_translate("MainWindow", "(X-ray - Laser)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

